CREATE TRIGGER CUSTOMER_BEFORE_UPDATE
BEFORE UPDATE
ON CUSTOMER
DECLARE
  V_USERNAME VARCHAR2(100);
BEGIN
  SELECT user INTO V_USERNAME FROM DUAL;  
  INSERT INTO AUDIT_TABLE(TABLE_NAME,USERID,OPERATION_DATE,OPERATION)
  VALUES('CUSTOMER',V_USERNAME,SYSDATE,'BEFORE UPDATE OPERATION');
END;


IMPLEMENTATION
=========================================================================

UPDATE CUSTOMER SET MIDDLE_NAME='SIMON' WHERE FIRST_NAME='PETER';
COMMIT;

--AUDIT TABLE
SELECT * FROM AUDIT_TABLE;
CUSTOMER	INVENTORY	24-SEP-23	BEFORE UPDATE OPERATION