CREATE OR REPLACE TRIGGER customer_after_update_values
AFTER UPDATE
ON CUSTOMER
FOR EACH ROW
DECLARE
  V_USERNAME VARCHAR2(100);
BEGIN
  SELECT user INTO V_USERNAME FROM DUAL;
  
  INSERT INTO AUDIT_LOG(USERID,OPERATION_DATE,B_CUSTOMERID,A_CUSTOMERID,B_FIRSTNAME,A_FIRSTNAME)
  VALUES(V_USERNAME,SYSDATE,:OLD.CUSTOMER_ID,:NEW.CUSTOMER_ID,:OLD.FIRST_NAME,:NEW.FIRST_NAME);
  
END;




======================================


UPDATE CUSTOMER SET first_name='JANET' WHERE first_name = 'JEFF';
COMMIT;

SELECT * FROM AUDIT_LOG;
INVENTORY	24-SEP-23	15	15	JEFF	JANET