CREATE OR REPLACE PROCEDURE CHECK_ELIGIBLE(P_ORDERID IN NUMBER , L_ELIGIBLE OUT BOOLEAN)
AS 
 L_TOTAL NUMBER;
BEGIN
 SELECT SUM(total_amount)INTO L_TOTAL
 FROM SALES
 WHERE 
  ORDER_ID = P_ORDERID;
  
 IF L_TOTAL >= 1000  THEN 
    L_ELIGIBLE := TRUE;
 END IF;    

END;
